version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd charity-connect
            npm install
      - run:
          name: Run tests
          command: |
            cd charity-connect
            npm run test
